# Node docker image on which this would be run
image: node:latest

variables:
   npm_config_cache: "$CI_PROJECT_DIR/.npm"
   NODE_ENV: 'test'



cache:
   key:
     files:
        - package.json
   paths:
      - .npm
      - node_modules

services:
   - mongo

stages:
  - install
  - build
  - test
  - staging
  - delivery
  - deployment

# Jobs:

install_dependencies:
  stage: install
  script:
    - npm  ci

Build_api:
  stage: build
  before_script:
     - npm run clean
  script:
    - npm run build

test_api:
  stage: test
  script:
    - npm test


stagin:
  stage: staging
  environment:
    name: deployment
    url: unruffled-jackson-964513.netlify.app
  script:
    - npm install
    - npm run build
  only:
    - master

staging:
  stage: staging
  environment:
    name: production
    url: laughing-wescoff-ebc91f.netlify.app
  script:
    - npm install
    - npm run build
  only:
    - develop
   
delivery:
  stage: delivery
  environment:
    name: production
    url: laughing-wescoff-ebc91f.netlify.app
  only:
    - develop
  script:
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  when : manual

deployment:
  stage: deployment
  environment:
    name: deployment
    url: unruffled-jackson-964513.netlify.app
  only:
    - master
  script:
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
